# Generated by Django 3.2.5 on 2021-08-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_payment_usercourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
